name: Licenses

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:

  deny-check:
    name: License check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.deps.dev:443
            api.github.com:443
            api.osv.dev:443
            api.scorecard.dev:443
            fulcio.sigstore.dev:443
            github.com:443
            oss-fuzz-build-logs.storage.googleapis.com:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443
            www.bestpractices.dev:443
            objects.githubusercontent.com:443
            static.rust-lang.org:443
            static.crates.io:443
            index.crates.io:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@315e265cd78dad1e1dcf3a5074f6d6c47029d5aa # nightly
        with:
          toolchain: nightly

      - name: Run cargo-deny
        uses: yonasBSD/toolkit@6647c8140a48bf1951edddd590006919066b626a # main
        with:
          run: |
            cargo-deny check licenses bans
            echo "::group::List of licenses"
            cargo-license --authors --do-not-bundle
            echo "::endgroup::"
            echo ### Licenses > $GITHUB_STEP_SUMMARY
            cargo-license --authors --do-not-bundle >> $GITHUB_STEP_SUMMARY
